image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - test
  - build

variables:
  project: "dotnet-react-calendar"

before_script:
  - "dotnet restore"
  - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
  - "apt-get install -y nodejs"
  - "npm install -g react"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"
  artifacts:
    paths:
      - build/

test:
  stage: test
  variables:
    test_path: "$project-test"
  script:
    - "cd $test_path"
    - "dotnet test"
