stages:
  - test
  - build
  - docker
  - deploy

variables:
  PROJECT: "dotnet-react-calendar"
  KUBECONFIG: /root/.kube/config

.dotnet_common: &dotnet_common
  - "dotnet restore"
  - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
  - "apt-get install -y nodejs"
  - "npm install -g react"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    build_path: "$PROJECT"
  script:
    - *dotnet_common
    - "cd $build_path"
    - sed -ie 's/<secrets.json>/${HERE_API_KEY}/g' appsettings.json
    - "dotnet publish -o ../artifacts/$PROJECT"
  artifacts:
    name: "$PROJECT-$CI_COMMIT_TAG"
    paths:
      - artifacts/$PROJECT

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    test_path: "$PROJECT-test"
  script:
    - *dotnet_common
    - "cd $test_path"
    - "dotnet test"

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_REGISTRY_USERNAME
    - echo "{\"auths\":{\"$DOCKER_REGISTRY_URL\":{\"auth\":\"$DOCKER_REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_REGISTRY_URL/$PROJECT:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKER_REGISTRY_URL/$PROJECT:latest

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  before_script:
    - sed -ie "s/deploy-date-value/$(date)/g" kubernetes/deployment.yaml
    - mkdir -p /root/.kube/ && touch /root/.kube/config
    - echo ${KUBERNETES_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl apply -f kubernetes/deployment.yaml
