image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - test
  - build
  - docker

variables:
  project: "dotnet-react-calendar"
  container_image: "https://gitlab.gregdyer.ca/homelab/dotnet-react-calendar:latest"

before_script:
  - "dotnet restore"
  - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
  - "apt-get install -y nodejs"
  - "npm install -g react"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"
  artifacts:
    paths:
      - bin/Release/net5.0/publish

test:
  stage: test
  variables:
    test_path: "$project-test"
  script:
    - "cd $test_path"
    - "dotnet test"

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
