stages:
  - test
  - build
  - docker

variables:
  project: "dotnet-react-calendar"
  container_image: "https://gitlab.gregdyer.ca/homelab/dotnet-react-calendar:latest"

.dotnet_common: &dotnet_common
  - "dotnet restore"
  - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
  - "apt-get install -y nodejs"
  - "npm install -g react"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    build_path: "$project"
  script:
    - *dotnet_common
    - "cd $build_path"
    - "dotnet build -o ../artifacts/$project"
  artifacts:
    name: "$project-$CI_COMMIT_TAG"
    paths:
      - artifacts/$project

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    test_path: "$project-test"
  script:
    - *dotnet_common
    - "cd $test_path"
    - "dotnet test"

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --insecure --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
